import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary:                     '#013e37',
        'primary-container':         '#015748',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#88deb1',
        secondary:                   '#013e37',
        'secondary-container':       '#88deb1',
        'on-secondary':              '#013e37',
        'on-secondary-container':    '#013e37',
        background:                  '#ffffff',
        surface:                     '#ffffff',
        'surface-dim':               '#d4f0e3',
        'surface-bright':            '#ffffff',
        'surface-container-low':     '#f0faf5',
        'surface-container':         '#e0f5ec',
        'surface-container-high':    '#c8edd9',
        'surface-container-highest': '#b4e4c8',
        'surface-container-lowest':  '#ffffff',
        'on-surface':                '#0a1a15',
        'on-surface-variant':        '#3d5047',
        'inverse-surface':           '#013e37',
        'inverse-on-surface':        '#e8f5ee',
        outline:                     '#6b8070',
        'outline-variant':           '#b8d4c4',
        'surface-tint':              '#013e37',
        tertiary:                    '#013e37',
        'tertiary-container':        '#015748',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#88deb1',
      },
      fontFamily: {
        display:  ['Lustra Text', 'sans-serif'],
        headline: ['Lustra Text', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':     ['56px', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['36px', { lineHeight: '1.1',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg':    ['32px', { lineHeight: '1.15', fontWeight: '700' }],
        'headline-md':    ['24px', { lineHeight: '1.3',  fontWeight: '700' }],
        'body-lg':        ['18px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-md':        ['16px', { lineHeight: '1.55', fontWeight: '400' }],
        'label-bold':     ['13px', { lineHeight: '1.0',  letterSpacing: '0.08em', fontWeight: '600' }],
      },
      spacing: {
        section:          '120px',
        'section-mobile': '80px',
        container:        '1280px',
        gutter:           '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        card:          '0px 2px 12px rgba(1, 62, 55, 0.06)',
        'card-hover':  '0px 8px 28px rgba(1, 62, 55, 0.13)',
        xl:            '0px 20px 48px rgba(1, 62, 55, 0.18)',
        'glow-mint':   '0px 0px 24px rgba(136, 222, 177, 0.35)',
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
